name: Publish package
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build source and binary distribution package
      run: |
        python setup.py sdist bdist_wheel
      env:
        PACKAGE_VERSION: ${{ github.ref }}

    - name: Check distribution package
      run: |
        twine check dist/*

    - name: Publish distribution package
      run: |
        twine upload dist/*
      env:
        TWINE_REPOSITORY: ${{ secrets.PYPI_REPOSITORY }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_NON_INTERACTIVE: yes
